description = 'error-handling-module'

dependencies {
    api 'org.springframework:spring-web'
    api 'org.springframework:spring-webmvc'
    api 'jakarta.servlet:jakarta.servlet-api'
    api 'jakarta.validation:jakarta.validation-api'
    compileOnly 'org.slf4j:slf4j-api'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-webmvc-test'
}
