package com.dochiri.security.application.exception;

public enum SecurityApplicationErrorCode {

    TOKEN_EXPIRED,
    TOKEN_MALFORMED,
    TOKEN_CATEGORY_INVALID,
    TOKEN_SUBJECT_MISSING,
    TOKEN_ROLE_MISSING,
    TOKEN_ID_MISSING,
    TOKEN_EXPIRATION_MISSING,
    TOKEN_CODEC_CONTRACT_VIOLATION,
    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_SUBJECT_MISMATCH,
    REFRESH_TOKEN_EXPIRATION_MISMATCH,
    REFRESH_TOKEN_INACTIVE,
    REFRESH_TOKEN_REVOCATION_COUNT_INVALID,
    REFRESH_SESSION_NOT_FOUND,
    REFRESH_SESSION_INACTIVE,
    REFRESH_TOKEN_ROLE_MISMATCH,
    REFRESH_TOKEN_REPLAYED,
    REFRESH_SESSION_ID_MISSING,
    REFRESH_SESSION_CLEANUP_BATCH_SIZE_INVALID,
    REFRESH_SESSION_CLEANUP_COUNT_INVALID
}
