plugins {
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'info.solidsoft.pitest' version '1.19.0' apply false
    id 'com.dochiri.lint-convention' version '1.0.0' apply false
}

allprojects {
    group = 'com.dochiri'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

configure(subprojects.findAll { it.path.startsWith(':modules:') }) {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'maven-publish'
    apply plugin: 'com.dochiri.lint-convention'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.3"
        }
    }

    publishing {
        repositories {
            mavenLocal()
        }

        publications {
            mavenJava(MavenPublication) {
                from components.java
                artifactId = "dochiri-${project.name}"

                versionMapping {
                    usage('java-api') { fromResolutionOf('runtimeClasspath') }
                    usage('java-runtime') { fromResolutionResult() }
                }
            }
        }
    }

    dependencies {
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
}

configure([
    project(':modules:security-domain'),
    project(':modules:security-application')
]) {
    apply plugin: 'info.solidsoft.pitest'

    pitest {
        junit5PluginVersion = '1.2.3'
        threads = Math.max(1, Runtime.runtime.availableProcessors().intdiv(2))
    }
}
