pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'multi-module'

include(
    'modules:api-starter',
    'modules:auth-server-starter',
    'modules:error-handling',
    'modules:gateway-security-starter',
    'modules:jpa',
    'modules:jpa-auditing',
    'modules:jpa-querydsl',
    'modules:security',
    'modules:security-domain',
    'modules:security-error-webmvc',
    'modules:security-application',
    'modules:security-jwt',
    'modules:security-jwt-issuer',
    'modules:security-webmvc',
    'modules:security-jpa',
    'modules:time'
)
