pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'multi-module'

include(
    'modules:error-handling-starter',
    'modules:jpa',
    'modules:jpa-auditing',
    'modules:jpa-querydsl',
    'modules:msa-auth-starter',
    'modules:msa-gateway-starter',
    'modules:security-domain',
    'modules:security-error-webmvc',
    'modules:security-application',
    'modules:security-jwt',
    'modules:security-jwt-issuer',
    'modules:security-webmvc',
    'modules:security-jpa',
    'modules:service-starter',
    'modules:time'
)
