description = 'security-jwt-issuer-adapter-module'

hexagonalConvention {
    basePackage = 'com.dochiri'
}

dependencies {
    api project(':modules:security-application')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
