package com.dochiri.security.domain.exception;

public enum SecurityDomainErrorCode {

    AUTHENTICATION_SUBJECT_REQUIRED,
    AUTHENTICATION_SUBJECT_BLANK,
    AUTHENTICATION_ROLE_REQUIRED,
    AUTHENTICATION_ROLE_BLANK,
    TOKEN_ID_REQUIRED,
    TOKEN_ID_BLANK,
    REFRESH_SESSION_ID_REQUIRED,
    REFRESH_SESSION_ID_BLANK,
    ENCODED_TOKEN_REQUIRED,
    ENCODED_TOKEN_BLANK,
    TOKEN_EXPIRATION_REQUIRED,
    CURRENT_TIME_REQUIRED,
    REVOKED_AT_REQUIRED,
    REFRESH_SESSION_STATUS_REQUIRED,
    REFRESH_SESSION_REVOKED_AT_REQUIRED,
    ACTIVE_SESSION_HAS_REVOKED_AT,
    REFRESH_SESSION_INACTIVE,
    REFRESH_TOKEN_REPLAYED,
    REFRESH_TOKEN_ROTATION_ID_UNCHANGED
}
