description = 'jpa-querydsl-module'

hexagonalConvention {
    basePackage = 'com.dochiri'
}

dependencies {
    api project(':modules:jpa-auditing')
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
}
